name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: |
        echo Hello, world and this!
        echo $GITHUB_WORKSPACE
        echo `ls $GITHUB_WORKSPACE`
        echo `pwd`
    - name: Decrypt large secret
      run: |
        gpg --quiet --batch --yes --decrypt --passphrase="$secret_key" --output google_auth.development.json google_auth.development.json.gpg
      env: 
        secret_key: ${{ secrets.encrypt_config_password }}
    - name: Test printing your secret (Remove this step in production)
      run: cat google_auth.development.json
