name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: |
        echo Hello, world and this!
        echo $HOME
    - name: Decrypt large secret
      run: |
        gpg --quiet --batch --yes --decrypt --passphrase=${{ secrets.encrypt_config_password}} --output $HOME/config/google_auth.development.json $HOME/config/google_auth.development.json.gpg
      env: 
        secret_key: ${{ secrets.encrypt_config_password }}
    - name: Test printing your secret (Remove this step in production)
      run: cat $HOME/config/google_auth.development.json
